name: Release
on:
  push:
    paths:
      - "version"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get relese version and image tag
        id: props
        run: |
          VERSION=$(cat version)
          echo "VERSION=$(cat version)" >> "$GITHUB_OUTPUT"
          echo "TAG=ghcr.io/${{ github.repository }}:$VERSION" >> "$GITHUB_OUTPUT"
      - name: Login to ghcr.io docker repository
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: docker build --tag ${{ steps.props.outputs.TAG }} .
      - name: Push Docker image to repository
        run: docker push ${{ steps.props.outputs.TAG }}
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.props.outputs.VERSION }}"
          name: "Release ${{ steps.props.outputs.VERSION }}"
          body: "Automated release triggered by version file change."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
